// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: anon_tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAnonToken = `-- name: CreateAnonToken :one
INSERT INTO anon_tokens (device_id, session_token, user_account_id, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, uuid, device_id, session_token, user_account_id, created_at, expires_at
`

type CreateAnonTokenParams struct {
	DeviceID      string             `json:"device_id"`
	SessionToken  string             `json:"session_token"`
	UserAccountID int64              `json:"user_account_id"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateAnonToken(ctx context.Context, arg CreateAnonTokenParams) (AnonToken, error) {
	row := q.db.QueryRow(ctx, createAnonToken,
		arg.DeviceID,
		arg.SessionToken,
		arg.UserAccountID,
		arg.ExpiresAt,
	)
	var i AnonToken
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.DeviceID,
		&i.SessionToken,
		&i.UserAccountID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteAnonTokensByUserAccountID = `-- name: DeleteAnonTokensByUserAccountID :exec
DELETE FROM anon_tokens
WHERE user_account_id = $1
`

func (q *Queries) DeleteAnonTokensByUserAccountID(ctx context.Context, userAccountID int64) error {
	_, err := q.db.Exec(ctx, deleteAnonTokensByUserAccountID, userAccountID)
	return err
}

const getAnonTokenBySessionToken = `-- name: GetAnonTokenBySessionToken :one
SELECT id, uuid, device_id, session_token, user_account_id, created_at, expires_at
FROM anon_tokens
WHERE session_token = $1
  AND expires_at > now()
`

func (q *Queries) GetAnonTokenBySessionToken(ctx context.Context, sessionToken string) (AnonToken, error) {
	row := q.db.QueryRow(ctx, getAnonTokenBySessionToken, sessionToken)
	var i AnonToken
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.DeviceID,
		&i.SessionToken,
		&i.UserAccountID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getAnonTokensByDeviceID = `-- name: GetAnonTokensByDeviceID :many
SELECT id, uuid, device_id, session_token, user_account_id, created_at, expires_at
FROM anon_tokens
WHERE device_id = $1
  AND expires_at > now()
ORDER BY created_at DESC
`

func (q *Queries) GetAnonTokensByDeviceID(ctx context.Context, deviceID string) ([]AnonToken, error) {
	rows, err := q.db.Query(ctx, getAnonTokensByDeviceID, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AnonToken
	for rows.Next() {
		var i AnonToken
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.DeviceID,
			&i.SessionToken,
			&i.UserAccountID,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
