// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: auth_oidc_identities.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countOIDCIdentitiesByUserAccount = `-- name: CountOIDCIdentitiesByUserAccount :one
SELECT count(*) FROM auth_oidc_identities WHERE user_account_id = $1
`

func (q *Queries) CountOIDCIdentitiesByUserAccount(ctx context.Context, userAccountID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countOIDCIdentitiesByUserAccount, userAccountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteOIDCIdentityByUUID = `-- name: DeleteOIDCIdentityByUUID :exec
DELETE FROM auth_oidc_identities
WHERE uuid = $1 AND user_account_id = $2
`

type DeleteOIDCIdentityByUUIDParams struct {
	Uuid          uuid.UUID `json:"uuid"`
	UserAccountID int64     `json:"user_account_id"`
}

func (q *Queries) DeleteOIDCIdentityByUUID(ctx context.Context, arg DeleteOIDCIdentityByUUIDParams) error {
	_, err := q.db.Exec(ctx, deleteOIDCIdentityByUUID, arg.Uuid, arg.UserAccountID)
	return err
}

const getOIDCIdentityByIssuerSubject = `-- name: GetOIDCIdentityByIssuerSubject :one
SELECT id, uuid, user_account_id, issuer, subject, email, email_verified_at_idp, linked_at, last_seen_at
FROM auth_oidc_identities
WHERE issuer = $1 AND subject = $2
`

type GetOIDCIdentityByIssuerSubjectParams struct {
	Issuer  string `json:"issuer"`
	Subject string `json:"subject"`
}

func (q *Queries) GetOIDCIdentityByIssuerSubject(ctx context.Context, arg GetOIDCIdentityByIssuerSubjectParams) (AuthOidcIdentity, error) {
	row := q.db.QueryRow(ctx, getOIDCIdentityByIssuerSubject, arg.Issuer, arg.Subject)
	var i AuthOidcIdentity
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserAccountID,
		&i.Issuer,
		&i.Subject,
		&i.Email,
		&i.EmailVerifiedAtIdp,
		&i.LinkedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const insertOIDCIdentity = `-- name: InsertOIDCIdentity :one
INSERT INTO auth_oidc_identities
  (user_account_id, issuer, subject, email, email_verified_at_idp)
VALUES
  ($1, $2, $3, $4, $5)
RETURNING id, uuid, user_account_id, issuer, subject, email, email_verified_at_idp, linked_at, last_seen_at
`

type InsertOIDCIdentityParams struct {
	UserAccountID      int64       `json:"user_account_id"`
	Issuer             string      `json:"issuer"`
	Subject            string      `json:"subject"`
	Email              pgtype.Text `json:"email"`
	EmailVerifiedAtIdp *time.Time  `json:"email_verified_at_idp"`
}

func (q *Queries) InsertOIDCIdentity(ctx context.Context, arg InsertOIDCIdentityParams) (AuthOidcIdentity, error) {
	row := q.db.QueryRow(ctx, insertOIDCIdentity,
		arg.UserAccountID,
		arg.Issuer,
		arg.Subject,
		arg.Email,
		arg.EmailVerifiedAtIdp,
	)
	var i AuthOidcIdentity
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserAccountID,
		&i.Issuer,
		&i.Subject,
		&i.Email,
		&i.EmailVerifiedAtIdp,
		&i.LinkedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const listOIDCIdentitiesByUserAccount = `-- name: ListOIDCIdentitiesByUserAccount :many
SELECT id, uuid, user_account_id, issuer, subject, email, email_verified_at_idp, linked_at, last_seen_at
FROM auth_oidc_identities
WHERE user_account_id = $1
ORDER BY linked_at ASC
`

func (q *Queries) ListOIDCIdentitiesByUserAccount(ctx context.Context, userAccountID int64) ([]AuthOidcIdentity, error) {
	rows, err := q.db.Query(ctx, listOIDCIdentitiesByUserAccount, userAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthOidcIdentity
	for rows.Next() {
		var i AuthOidcIdentity
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.UserAccountID,
			&i.Issuer,
			&i.Subject,
			&i.Email,
			&i.EmailVerifiedAtIdp,
			&i.LinkedAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchOIDCIdentityLastSeen = `-- name: TouchOIDCIdentityLastSeen :exec
UPDATE auth_oidc_identities
SET last_seen_at = now()
WHERE id = $1
`

func (q *Queries) TouchOIDCIdentityLastSeen(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, touchOIDCIdentityLastSeen, id)
	return err
}
