// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_jwt_secrets.sql

package db

import (
	"context"
)

const getJWTSecret = `-- name: GetJWTSecret :one
SELECT secret FROM auth_jwt_secrets WHERE id = 1
`

func (q *Queries) GetJWTSecret(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, getJWTSecret)
	var secret string
	err := row.Scan(&secret)
	return secret, err
}

const insertJWTSecretIfAbsent = `-- name: InsertJWTSecretIfAbsent :one
INSERT INTO auth_jwt_secrets (id, secret)
VALUES (1, $1)
ON CONFLICT (id) DO NOTHING
RETURNING secret
`

func (q *Queries) InsertJWTSecretIfAbsent(ctx context.Context, secret string) (string, error) {
	row := q.db.QueryRow(ctx, insertJWTSecretIfAbsent, secret)
	var secret_2 string
	err := row.Scan(&secret_2)
	return secret_2, err
}
