// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ssh_public_keys.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const archiveSSHPublicKey = `-- name: ArchiveSSHPublicKey :execrows
UPDATE mod_users.ssh_public_keys
SET archived_at = now()
WHERE uuid = $1 AND user_account_id = $2 AND archived_at IS NULL
`

type ArchiveSSHPublicKeyParams struct {
	Uuid          uuid.UUID `json:"uuid"`
	UserAccountID int64     `json:"user_account_id"`
}

func (q *Queries) ArchiveSSHPublicKey(ctx context.Context, arg ArchiveSSHPublicKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, archiveSSHPublicKey, arg.Uuid, arg.UserAccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countActiveSSHPublicKeysByUserAccount = `-- name: CountActiveSSHPublicKeysByUserAccount :one
SELECT count(*)
FROM mod_users.ssh_public_keys
WHERE user_account_id = $1 AND archived_at IS NULL
`

func (q *Queries) CountActiveSSHPublicKeysByUserAccount(ctx context.Context, userAccountID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveSSHPublicKeysByUserAccount, userAccountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getActiveSSHPublicKeyByUUIDForUserAccount = `-- name: GetActiveSSHPublicKeyByUUIDForUserAccount :one
SELECT id, uuid, user_account_id, key_type, public_key, fingerprint_sha256,
       label, created_at, archived_at
FROM mod_users.ssh_public_keys
WHERE uuid = $1 AND user_account_id = $2 AND archived_at IS NULL
`

type GetActiveSSHPublicKeyByUUIDForUserAccountParams struct {
	Uuid          uuid.UUID `json:"uuid"`
	UserAccountID int64     `json:"user_account_id"`
}

func (q *Queries) GetActiveSSHPublicKeyByUUIDForUserAccount(ctx context.Context, arg GetActiveSSHPublicKeyByUUIDForUserAccountParams) (ModUsersSshPublicKey, error) {
	row := q.db.QueryRow(ctx, getActiveSSHPublicKeyByUUIDForUserAccount, arg.Uuid, arg.UserAccountID)
	var i ModUsersSshPublicKey
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserAccountID,
		&i.KeyType,
		&i.PublicKey,
		&i.FingerprintSha256,
		&i.Label,
		&i.CreatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const insertSSHPublicKey = `-- name: InsertSSHPublicKey :one
INSERT INTO mod_users.ssh_public_keys
  (user_account_id, key_type, public_key, fingerprint_sha256, label)
VALUES
  ($1, $2, $3, $4, $5)
RETURNING id, uuid, user_account_id, key_type, public_key, fingerprint_sha256,
          label, created_at, archived_at
`

type InsertSSHPublicKeyParams struct {
	UserAccountID     int64  `json:"user_account_id"`
	KeyType           string `json:"key_type"`
	PublicKey         string `json:"public_key"`
	FingerprintSha256 string `json:"fingerprint_sha256"`
	Label             string `json:"label"`
}

func (q *Queries) InsertSSHPublicKey(ctx context.Context, arg InsertSSHPublicKeyParams) (ModUsersSshPublicKey, error) {
	row := q.db.QueryRow(ctx, insertSSHPublicKey,
		arg.UserAccountID,
		arg.KeyType,
		arg.PublicKey,
		arg.FingerprintSha256,
		arg.Label,
	)
	var i ModUsersSshPublicKey
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserAccountID,
		&i.KeyType,
		&i.PublicKey,
		&i.FingerprintSha256,
		&i.Label,
		&i.CreatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const listActiveSSHPublicKeysByUserAccount = `-- name: ListActiveSSHPublicKeysByUserAccount :many
SELECT id, uuid, user_account_id, key_type, public_key, fingerprint_sha256,
       label, created_at, archived_at
FROM mod_users.ssh_public_keys
WHERE user_account_id = $1 AND archived_at IS NULL
ORDER BY created_at ASC, id ASC
LIMIT $2 OFFSET $3
`

type ListActiveSSHPublicKeysByUserAccountParams struct {
	UserAccountID int64 `json:"user_account_id"`
	Limit         int32 `json:"limit"`
	Offset        int32 `json:"offset"`
}

func (q *Queries) ListActiveSSHPublicKeysByUserAccount(ctx context.Context, arg ListActiveSSHPublicKeysByUserAccountParams) ([]ModUsersSshPublicKey, error) {
	rows, err := q.db.Query(ctx, listActiveSSHPublicKeysByUserAccount, arg.UserAccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ModUsersSshPublicKey
	for rows.Next() {
		var i ModUsersSshPublicKey
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.UserAccountID,
			&i.KeyType,
			&i.PublicKey,
			&i.FingerprintSha256,
			&i.Label,
			&i.CreatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveActiveSSHPublicKey = `-- name: ResolveActiveSSHPublicKey :one
SELECT ua.account_holder
FROM mod_users.ssh_public_keys k
JOIN public.user_accounts ua ON ua.id = k.user_account_id
WHERE k.fingerprint_sha256 = $1 AND k.public_key = $2 AND k.archived_at IS NULL
`

type ResolveActiveSSHPublicKeyParams struct {
	FingerprintSha256 string `json:"fingerprint_sha256"`
	PublicKey         string `json:"public_key"`
}

func (q *Queries) ResolveActiveSSHPublicKey(ctx context.Context, arg ResolveActiveSSHPublicKeyParams) (int64, error) {
	row := q.db.QueryRow(ctx, resolveActiveSSHPublicKey, arg.FingerprintSha256, arg.PublicKey)
	var account_holder int64
	err := row.Scan(&account_holder)
	return account_holder, err
}
