// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: system_actors.sql

package db

import (
	"context"
)

const getSystemActorBySlug = `-- name: GetSystemActorBySlug :one
SELECT entity_id, slug FROM system_actors WHERE slug = $1
`

type GetSystemActorBySlugRow struct {
	EntityID int64  `json:"entity_id"`
	Slug     string `json:"slug"`
}

func (q *Queries) GetSystemActorBySlug(ctx context.Context, slug string) (GetSystemActorBySlugRow, error) {
	row := q.db.QueryRow(ctx, getSystemActorBySlug, slug)
	var i GetSystemActorBySlugRow
	err := row.Scan(&i.EntityID, &i.Slug)
	return i, err
}
