package auth

import (
	"context"
	"encoding/json"
	"errors"
	"net/http"
	"net/http/httptest"
	"testing"
	"time"

	"github.com/golang-jwt/jwt/v5"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"

	"github.com/moduleforge/core-api/opctx"
	db "github.com/moduleforge/mod-users/model/db"
)

// -----------------------------------------------------------------------
// Characterization tests for RequireAuth.
//
// These tests pin every branch of RequireAuth's current, pre-refactor
// behavior (status code, exact response body, whether `next` ran, and the
// context values set on success) so that the extraction of the shared
// error-mapping and success-population logic into helpers (task
// phase-01-anonymous-actor/003) cannot silently change observable
// behavior. Do not edit this file to make a refactor pass — if a refactor
// changes what these tests assert, the refactor introduced a regression.
// -----------------------------------------------------------------------

// requireAuthSecret and requireAuthIssuer are the local-JWT secret/issuer
// used to construct the Verifier and UserResolver under test, matching how
// api/cmd/server/main.go wires RequireAuth's dependencies in local-only mode.
const (
	requireAuthSecret = "requireauth-characterization-secret"
	requireAuthIssuer = "requireauth-characterization-issuer"
)

// requireAuthCaptureHandler is a next-handler stand-in that records whether
// it ran and captures the *request context* it was called with, so tests can
// assert on the context values RequireAuth populates (FromContext, opctx
// actor/sudo-actor) without needing a real downstream handler.
type requireAuthCaptureHandler struct {
	called bool
	ctx    context.Context
}

func (h *requireAuthCaptureHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	h.called = true
	h.ctx = r.Context()
	w.WriteHeader(http.StatusOK)
}

// newRequireAuthVerifier builds a local-only Verifier exactly as
// api/cmd/server/main.go wires it for RequireAuth (empty issuerURL/clientID
// disables OIDC verification; only local HS256 tokens verify).
func newRequireAuthVerifier(t *testing.T) *Verifier {
	t.Helper()
	v, err := NewVerifier(context.Background(), "", "", requireAuthSecret, requireAuthIssuer)
	if err != nil {
		t.Fatalf("NewVerifier: %v", err)
	}
	return v
}

// newRequireAuthMapper builds the same "generic" ClaimMapper style and path
// configuration api/cmd/server/main.go wires for the local JWT's flat
// "email"/"roles" claims.
func newRequireAuthMapper(t *testing.T) ClaimMapper {
	t.Helper()
	m, err := NewClaimMapper("generic", MapperOptions{
		EmailPath: "email",
		RolesPath: "roles",
	})
	if err != nil {
		t.Fatalf("NewClaimMapper: %v", err)
	}
	return m
}

// signRequireAuthToken mints an HS256 JWT signed with the given secret,
// directly via jwt.NewWithClaims — the pattern jwt_test.go uses.
func signRequireAuthToken(t *testing.T, secret string, claims jwt.MapClaims) string {
	t.Helper()
	tok := jwt.NewWithClaims(jwt.SigningMethodHS256, claims)
	raw, err := tok.SignedString([]byte(secret))
	if err != nil {
		t.Fatalf("sign token: %v", err)
	}
	return raw
}

// requireAuthBaseClaims returns the mandatory claims (sub, iss, iat, exp)
// for a validly-formed local JWT, valid for one hour from now.
func requireAuthBaseClaims(sub string) jwt.MapClaims {
	return jwt.MapClaims{
		"sub": sub,
		"iss": requireAuthIssuer,
		"iat": time.Now().Unix(),
		"exp": time.Now().Add(time.Hour).Unix(),
	}
}

// requireAuthErrorBody mirrors the wire shape server.Error / apiresp.Envelope
// writes: {"error": {"code": ..., "message": ...}}.
type requireAuthErrorBody struct {
	Error struct {
		Code    string `json:"code"`
		Message string `json:"message"`
	} `json:"error"`
}

func decodeRequireAuthErrorBody(t *testing.T, rec *httptest.ResponseRecorder) requireAuthErrorBody {
	t.Helper()
	var body requireAuthErrorBody
	if err := json.NewDecoder(rec.Body).Decode(&body); err != nil {
		t.Fatalf("decode error body: %v (raw body: %s)", err, rec.Body.String())
	}
	return body
}

// -----------------------------------------------------------------------
// Fake DBTX for the AssumedUser (sudo) success case.
//
// resolver.buildUserContext looks up the sudo user via r.queries directly
// (not via the injectable uuidLookup stub used for the primary-user lookup),
// so exercising RequireAuth's AssumedUser context-population branch without
// a real database requires a minimal fake db.DBTX whose QueryRow answers
// GetUserAccountByUUID with a fixed row. No network or database is used.
// -----------------------------------------------------------------------

// sudoAccountDBTX is a db.DBTX stub that answers every QueryRow call with a
// fixed db.UserAccount row, regardless of the query/args — sufficient here
// because the only query issued against it in these tests is the sudo-user
// lookup in resolver.buildUserContext.
type sudoAccountDBTX struct {
	account db.UserAccount
}

func (f sudoAccountDBTX) Exec(ctx context.Context, sql string, args ...any) (pgconn.CommandTag, error) {
	return pgconn.CommandTag{}, errors.New("sudoAccountDBTX: Exec not implemented")
}

func (f sudoAccountDBTX) Query(ctx context.Context, sql string, args ...any) (pgx.Rows, error) {
	return nil, errors.New("sudoAccountDBTX: Query not implemented")
}

func (f sudoAccountDBTX) QueryRow(ctx context.Context, sql string, args ...any) pgx.Row {
	return sudoAccountRow{account: f.account}
}

// sudoAccountRow implements pgx.Row over a single db.UserAccount, scanning
// its fields in the same order sqlc's GetUserAccountByUUID emits (see
// model/db/user_accounts.sql.go).
type sudoAccountRow struct {
	account db.UserAccount
}

func (r sudoAccountRow) Scan(dest ...any) error {
	src := []any{
		r.account.ID,
		r.account.Uuid,
		r.account.AccountHolder,
		r.account.Email,
		r.account.EmailVerifiedAt,
		r.account.DefaultAppID,
		r.account.CreatedAt,
		r.account.UpdatedAt,
	}
	if len(dest) != len(src) {
		return errors.New("sudoAccountRow: scan arg count mismatch")
	}
	for i, d := range dest {
		switch d := d.(type) {
		case *int64:
			*d = src[i].(int64)
		case *uuid.UUID:
			*d = src[i].(uuid.UUID)
		case *pgtype.Text:
			*d = src[i].(pgtype.Text)
		case **time.Time:
			*d = src[i].(*time.Time)
		case *pgtype.Int8:
			*d = src[i].(pgtype.Int8)
		case *pgtype.Timestamptz:
			*d = src[i].(pgtype.Timestamptz)
		default:
			return errors.New("sudoAccountRow: unsupported scan dest type")
		}
	}
	return nil
}

// -----------------------------------------------------------------------
// The characterization table.
// -----------------------------------------------------------------------

func TestRequireAuth(t *testing.T) {
	primaryUUID := uuid.New()
	primaryUA := db.UserAccount{
		ID:            42,
		Uuid:          primaryUUID,
		AccountHolder: 501,
		Email:         pgtype.Text{String: "user@example.com", Valid: true},
	}

	sudoUUID := uuid.New()
	sudoUA := db.UserAccount{
		ID:            99,
		Uuid:          sudoUUID,
		AccountHolder: 777,
		Email:         pgtype.Text{String: "admin@example.com", Valid: true},
	}

	deletedUUID := uuid.New()
	lookupFailUUID := uuid.New()

	type testCase struct {
		name string
		// header returns the Authorization header value to set, or "" to
		// omit the header entirely.
		header func(t *testing.T) string
		// resolver builds the *UserResolver for this case. May be a
		// never-invoked placeholder for cases that fail before Resolve is
		// reached.
		resolver func(t *testing.T) *UserResolver

		wantStatus     int
		wantCode       string
		wantMessage    string
		wantNextCalled bool

		// checkSuccessCtx runs only when wantNextCalled is true; it
		// inspects the context handed to `next`.
		checkSuccessCtx func(t *testing.T, ctx context.Context)
	}

	cases := []testCase{
		{
			name:           "no Authorization header",
			header:         func(t *testing.T) string { return "" },
			resolver:       func(t *testing.T) *UserResolver { return &UserResolver{} },
			wantStatus:     http.StatusUnauthorized,
			wantCode:       "unauthorized",
			wantMessage:    "missing Authorization header",
			wantNextCalled: false,
		},
		{
			name:           "Authorization header present but not Bearer form",
			header:         func(t *testing.T) string { return "Basic dXNlcjpwYXNz" },
			resolver:       func(t *testing.T) *UserResolver { return &UserResolver{} },
			wantStatus:     http.StatusUnauthorized,
			wantCode:       "unauthorized",
			wantMessage:    "invalid Authorization header format",
			wantNextCalled: false,
		},
		{
			name: "Bearer token rejected: bad signature",
			header: func(t *testing.T) string {
				raw := signRequireAuthToken(t, "wrong-secret-entirely", requireAuthBaseClaims(primaryUUID.String()))
				return "Bearer " + raw
			},
			resolver:       func(t *testing.T) *UserResolver { return &UserResolver{} },
			wantStatus:     http.StatusUnauthorized,
			wantCode:       "unauthorized",
			wantMessage:    "invalid or expired token",
			wantNextCalled: false,
		},
		{
			name: "Bearer token rejected: expired",
			header: func(t *testing.T) string {
				claims := requireAuthBaseClaims(primaryUUID.String())
				claims["exp"] = time.Now().Add(-time.Hour).Unix()
				raw := signRequireAuthToken(t, requireAuthSecret, claims)
				return "Bearer " + raw
			},
			resolver:       func(t *testing.T) *UserResolver { return &UserResolver{} },
			wantStatus:     http.StatusUnauthorized,
			wantCode:       "unauthorized",
			wantMessage:    "invalid or expired token",
			wantNextCalled: false,
		},
		{
			name: "resolver returns ErrUserGone",
			header: func(t *testing.T) string {
				claims := requireAuthBaseClaims(deletedUUID.String())
				raw := signRequireAuthToken(t, requireAuthSecret, claims)
				return "Bearer " + raw
			},
			resolver: func(t *testing.T) *UserResolver {
				lookup := func(ctx context.Context, u uuid.UUID) (db.UserAccount, error) {
					return db.UserAccount{}, pgx.ErrNoRows
				}
				return newResolverWithStub(t, requireAuthIssuer, lookup)
			},
			wantStatus:     http.StatusUnauthorized,
			wantCode:       "unauthorized",
			wantMessage:    "user no longer exists",
			wantNextCalled: false,
		},
		{
			name: "claim mapper fails (missing sub claim)",
			header: func(t *testing.T) string {
				// A validly-signed, validly-issued, unexpired token that is
				// missing the mandatory "sub" claim: verifier.Verify
				// succeeds (it never inspects "sub"), but mapper.Map fails
				// in extractRequired, producing an AuthenticateRequest
				// error prefixed "claim map:".
				claims := jwt.MapClaims{
					"iss": requireAuthIssuer,
					"iat": time.Now().Unix(),
					"exp": time.Now().Add(time.Hour).Unix(),
				}
				raw := signRequireAuthToken(t, requireAuthSecret, claims)
				return "Bearer " + raw
			},
			resolver:       func(t *testing.T) *UserResolver { return &UserResolver{} },
			wantStatus:     http.StatusInternalServerError,
			wantCode:       "internal_error",
			wantMessage:    "failed to process authentication claims",
			wantNextCalled: false,
		},
		{
			name: "resolver returns other internal error",
			header: func(t *testing.T) string {
				raw := signRequireAuthToken(t, requireAuthSecret, requireAuthBaseClaims(lookupFailUUID.String()))
				return "Bearer " + raw
			},
			resolver: func(t *testing.T) *UserResolver {
				lookup := func(ctx context.Context, u uuid.UUID) (db.UserAccount, error) {
					return db.UserAccount{}, errors.New("db: connection reset")
				}
				return newResolverWithStub(t, requireAuthIssuer, lookup)
			},
			wantStatus:     http.StatusInternalServerError,
			wantCode:       "internal_error",
			wantMessage:    "failed to resolve user",
			wantNextCalled: false,
		},
		{
			name: "success, no assumed user",
			header: func(t *testing.T) string {
				raw := signRequireAuthToken(t, requireAuthSecret, requireAuthBaseClaims(primaryUUID.String()))
				return "Bearer " + raw
			},
			resolver: func(t *testing.T) *UserResolver {
				lookup := func(ctx context.Context, u uuid.UUID) (db.UserAccount, error) {
					if u != primaryUUID {
						t.Errorf("uuidLookup got %s, want %s", u, primaryUUID)
					}
					return primaryUA, nil
				}
				return newResolverWithStub(t, requireAuthIssuer, lookup)
			},
			wantStatus:     http.StatusOK,
			wantNextCalled: true,
			checkSuccessCtx: func(t *testing.T, ctx context.Context) {
				uc, ok := FromContext(ctx)
				if !ok {
					t.Fatal("expected *UserContext on request context")
				}
				if uc.EntityID != primaryUA.AccountHolder {
					t.Errorf("uc.EntityID = %d, want %d", uc.EntityID, primaryUA.AccountHolder)
				}
				actorID, ok := opctx.ActorEntityID(ctx)
				if !ok {
					t.Fatal("expected opctx actor entity id to be set")
				}
				if actorID != uc.EntityID {
					t.Errorf("opctx.ActorEntityID = %d, want %d (uc.EntityID)", actorID, uc.EntityID)
				}
				if _, ok := opctx.SudoActorEntityID(ctx); ok {
					t.Error("expected opctx sudo actor entity id to be unset")
				}
			},
		},
		{
			name: "success, AssumedUser set",
			header: func(t *testing.T) string {
				claims := requireAuthBaseClaims(primaryUUID.String())
				claims["sudo_user_uuid"] = sudoUUID.String()
				raw := signRequireAuthToken(t, requireAuthSecret, claims)
				return "Bearer " + raw
			},
			resolver: func(t *testing.T) *UserResolver {
				lookup := func(ctx context.Context, u uuid.UUID) (db.UserAccount, error) {
					if u != primaryUUID {
						t.Errorf("uuidLookup got %s, want %s", u, primaryUUID)
					}
					return primaryUA, nil
				}
				r := newResolverWithStub(t, requireAuthIssuer, lookup)
				r.queries = db.New(sudoAccountDBTX{account: sudoUA})
				return r
			},
			wantStatus:     http.StatusOK,
			wantNextCalled: true,
			checkSuccessCtx: func(t *testing.T, ctx context.Context) {
				uc, ok := FromContext(ctx)
				if !ok {
					t.Fatal("expected *UserContext on request context")
				}
				if uc.AssumedUser == nil {
					t.Fatal("expected uc.AssumedUser to be populated")
				}
				if uc.AssumedUser.EntityID != sudoUA.AccountHolder {
					t.Errorf("uc.AssumedUser.EntityID = %d, want %d", uc.AssumedUser.EntityID, sudoUA.AccountHolder)
				}
				actorID, ok := opctx.ActorEntityID(ctx)
				if !ok {
					t.Fatal("expected opctx actor entity id to be set")
				}
				if actorID != uc.EntityID {
					t.Errorf("opctx.ActorEntityID = %d, want %d (uc.EntityID, not the sudo actor)", actorID, uc.EntityID)
				}
				sudoID, ok := opctx.SudoActorEntityID(ctx)
				if !ok {
					t.Fatal("expected opctx sudo actor entity id to be set")
				}
				if sudoID != uc.AssumedUser.EntityID {
					t.Errorf("opctx.SudoActorEntityID = %d, want %d", sudoID, uc.AssumedUser.EntityID)
				}
			},
		},
	}

	verifier := newRequireAuthVerifier(t)
	mapper := newRequireAuthMapper(t)

	for _, tc := range cases {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()

			resolver := tc.resolver(t)
			next := &requireAuthCaptureHandler{}
			mw := RequireAuth(verifier, mapper, resolver)(next)

			req := httptest.NewRequest(http.MethodGet, "/v1/test", nil)
			if h := tc.header(t); h != "" {
				req.Header.Set("Authorization", h)
			}
			rec := httptest.NewRecorder()

			mw.ServeHTTP(rec, req)

			if next.called != tc.wantNextCalled {
				t.Fatalf("next.called = %v, want %v", next.called, tc.wantNextCalled)
			}
			if rec.Code != tc.wantStatus {
				t.Fatalf("status = %d, want %d (body: %s)", rec.Code, tc.wantStatus, rec.Body.String())
			}

			if tc.wantNextCalled {
				if tc.checkSuccessCtx != nil {
					tc.checkSuccessCtx(t, next.ctx)
				}
				return
			}

			body := decodeRequireAuthErrorBody(t, rec)
			if body.Error.Code != tc.wantCode {
				t.Errorf("error.code = %q, want %q", body.Error.Code, tc.wantCode)
			}
			if body.Error.Message != tc.wantMessage {
				t.Errorf("error.message = %q, want %q", body.Error.Message, tc.wantMessage)
			}
		})
	}
}
